version: '3.8'

services:
  api:
    image: adamdevigili/skillbased:api
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env.prod

  frontend:
    image: adamdevigili/skillbased:frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api
    env_file:
      - .env.prod
  # Proxies requests to internal services
  nginx:
    image: adamdevigili/skillbased:nginx
    restart: always
    depends_on:
      - frontend
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    env_file:
      - .env.prod

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email adamdevigili@skillbased.xyz --agree-tos --no-eff-email --force-renewal -d skillbased.xyz -d www.skillbased.xyz -d api.skillbased.xyz

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: ~/skillbased
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: ~/skillbased/dhparam/
      o: bind
