version: '3.8'

services:
  # Go API
  api:
    build: ./api
    # image: adamdevigili/skillbased:api
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env.local
    links:
    - db

  # Node/NextJS
  frontend:
    # build: ./frontend
    image: adamdevigili/skillbased:frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api
    env_file:
      - .env.local

  # Proxies requests to internal services
  # nginx:
  #   image: adamdevigili/skillbased:nginx
  #   restart: always
  #   depends_on:
  #     - frontend
  #     - api
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - web-root:/var/www/html
  #     - certbot-etc:/etc/letsencrypt
  #     - certbot-var:/var/lib/letsencrypt
  #     - dhparam:/etc/ssl/certs
  #   env_file:
  #     - .env.local

  # Auto TLS
  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - certbot-var:/var/lib/letsencrypt
  #     - web-root:/var/www/html
  #   depends_on:
  #     - nginx
  #   command: certonly --webroot --webroot-path=/var/www/html --email adamdevigili@skillbased.xyz --agree-tos --no-eff-email --force-renewal -d skillbased.xyz -d www.skillbased.xyz -d api.skillbased.xyz

  db:
    image: postgres:14-alpine
    ports:
      - "8001:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: skillbased
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      
volumes:
  postgres:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: ~/skillbased
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: ~/skillbased/dhparam/
      o: bind
