version: '3.8'

services:

  api:
    image: adamdevigili/skillbased:api
    ports:
      - "8080:8080"
    env_file:
      - ./api/.env

  frontend:
    image: adamdevigili/skillbased:frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy_demo
    depends_on:
      - frontend
      - api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

#  nginx:
#    image: adamdevigili/skillbased:nginx
#    ports:
#      - "80:80"
#    env_file:
#      - .env
