package main

import (
	"embed"
	"flag"
	"fmt"
	"io/fs"
	"net/http"

	"github.com/adamdevigili/skillbased/api/pkg/db"
	_ "github.com/adamdevigili/skillbased/api/pkg/db"
	"github.com/adamdevigili/skillbased/api/pkg/server"
	"github.com/jinzhu/gorm"
	"github.com/labstack/echo/v4"
	"github.com/labstack/gommon/log"
)

//go:embed frontend/dist
//go:embed frontend/dist/_next
//go:embed frontend/dist/_next/static/chunks/pages/*.js
//go:embed frontend/dist/_next/static/*/*.js
var nextFS embed.FS

/*
 */

func main() {
	// Root at the `dist` folder generated by the Next.js app.
	distFS, err := fs.Sub(nextFS, "frontend/dist")
	if err != nil {
		log.Fatal(err)
	}

	staticFS := http.FileServer(http.FS(distFS))

	// The static Next.js app will be served under `/`.
	// http.Handle("/", http.FileServer(http.FS(distFS)))

	// log.Println("Starting HTTP server at http://localhost:8080 ...")
	// go http.ListenAndServe(":8080", nil)

	// log.Fatal()
	// fmt.Println()

	// The static Next.js app will be served under `/`.
	// http.Handle("/", )

	// // Start HTTP server at :8080.
	// log.Println("Starting HTTP server at http://localhost:8080 ...")
	// log.Fatal(http.ListenAndServe(":9000", nil))

	// Create new Echo server
	e := echo.New()

	noDB := flag.Bool("no-db", false, "run this server without connecting to a database")
	port := flag.String("port", "8080", "port to serve on")
	flag.Parse()

	var pg *gorm.DB
	if !*noDB {
		pg = db.InitDB()
	} else {
		log.Infof("starting without database connection")
	}

	// Initialize DB and routes
	server.InitRoutes(e, pg, &staticFS)

	// Start server
	e.Logger.Fatal(e.Start(fmt.Sprintf(":%s", *port)))
}
