package main

import (
	"embed"
	"io/fs"
	"log"
	"net/http"

	"github.com/adamdevigili/skillbased/api/pkg/db"
	"github.com/adamdevigili/skillbased/api/pkg/server"
	"github.com/labstack/echo/v4"
)

//go:embed frontend/dist
//go:embed frontend/dist/_next
//go:embed frontend/dist/_next/static/chunks/pages/*.js
//go:embed frontend/dist/_next/static/*/*.js
var nextFS embed.FS

/*
 */

func main() {
	// Root at the `dist` folder generated by the Next.js app.
	distFS, err := fs.Sub(nextFS, "frontend/dist")
	if err != nil {
		log.Fatal(err)
	}

	staticFS := http.FileServer(http.FS(distFS))

	// The static Next.js app will be served under `/`.
	// http.Handle("/", http.FileServer(http.FS(distFS)))

	// log.Println("Starting HTTP server at http://localhost:8080 ...")
	// go http.ListenAndServe(":8080", nil)

	// log.Fatal()
	// fmt.Println()

	// The static Next.js app will be served under `/`.
	// http.Handle("/", )

	// // Start HTTP server at :8080.
	// log.Println("Starting HTTP server at http://localhost:8080 ...")
	// log.Fatal(http.ListenAndServe(":9000", nil))

	// Create new Echo server
	e := echo.New()

	// Initialize DB and routes
	server.InitRoutes(e, db.InitDB(), &staticFS)

	// Start server
	e.Logger.Fatal(e.Start(":8080"))
}
