version: '2'

services:
  postgres:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: test
      POSTGRES_DB: skillbased
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  skillbased-api:
    container_name: skillbased-api
    # Use this if you want to run against upstream latest image
    #image: adamdevigili/balancer.team-api:latest
    build:
      context: ../../backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: user
      PG_PASSWORD: test
      PG_DATABASE: skillbased

  skillbased-ui-nginx:
    container_name: skillbased-ui-nginx
    build:
      context: ../..
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
